# Bonfire deployment configuration
# Defines where to fetch the file that defines application configs

appsFile:
  host: github
  repo: RedHatInsights/cicd-common
  path: bonfire_configs/ephemeral_apps.yaml

apps:
- name: ccx-data-pipeline
  components:
    - name: ccx-data-pipeline
      host: github
      repo: RedHatInsights/ccx-data-pipeline
      path: deploy/clowdapp.yaml
      ref: master
      parameters:
        CLOWDER_ENABLED: "true"
        IMAGE_TAG: qa
    - name: ccx-insights-results
      host: github
      repo: RedHatInsights/insights-results-aggregator
      path: deploy/clowdapp.yaml
      ref: master
      parameters:
        CLOWDER_ENABLED: "true"
        IMAGE_TAG: qa
    - name: ccx-insights-results-aggregator-cleaner
      host: github
      repo: <user>/insights-results-aggregator-cleaner
      path: deploy/clowdapp.yaml
      ref: master
      parameters:
        CLOWDER_ENABLED: "true"
        IMAGE_TAG: latest
