[storage]
db_driver = "postgres"
pg_username = "postgres"
pg_password = "postgres"
pg_host = "localhost"
pg_port = 5432
pg_db_name = "aggregator"
pg_params = "sslmode=disable"
schema = "ocp_recommendations"

[logging]
debug = true
log_level = ""
logging_to_sentry_enabled = false

[cleaner]
max_age = "90 days"
cluster_list_file = "cluster_list.txt"

[sentry]
dsn = ""
environment = "dev"
